### ISSUE TITLE
check if progress has been saved before quitting

### ISSUE THREAD

**Issue by ngreenwald** [vanvalenlab/caliban#100]
In order to avoid losing work, would be nice to check if the current version is saved when caliban exits. 

Could either check to see if current segmentation is identical to last saved version, or prompt user to save/overwrite when they exit

**Comment by geneva-miller** [comment]
I think this issue is a duplicate of #84. It's not an immediate priority but if I have time to figure out that aspect of pyglet window behavior, the rest should be straightforward.

**Comment by ngreenwald** [comment]
woops, good call!
