### ISSUE TITLE
default parameters when opening caliban

### ISSUE THREAD

**Issue by ngreenwald** [vanvalenlab/caliban#101]
Minor tweak, but I think it would be useful to have caliban -rgb initialize with the following settings:

In labels mode, have the default be that labels are shown, and that it's the contour overlay view of labels. 

In pixel edit mode, have the brush size start as 3 or 4 instead of 1.

**Comment by geneva-miller** [comment]
I've pushed these changes so that RGB caliban opens on the label contour overlay. Brush is now initialized with size 5.

**Comment by ngreenwald** [comment]
awesome, thanks!
