### ISSUE TITLE
rgb mode rendering/image thresholding issue

### ISSUE THREAD

**Issue by ngreenwald** [vanvalenlab/caliban#104]
I can't figure out exactly what is causing this, but the newest batch of IF data has a weird thresholding artifact when displayed in caliban. Below is what I see when plotting the contents of the NPZ:

![image](https://user-images.githubusercontent.com/13770365/76390082-fa28ac80-6329-11ea-9d15-a48c7010f968.png)

And here is what I see in caliban: 
![image](https://user-images.githubusercontent.com/13770365/76390131-10cf0380-632a-11ea-8a9a-a627e4733299.png)

It looks like the values are being capped, which is what leads to the contour-like effect. This image has values up to 800, which is brighter than normal MIBI images. However, when I rescaled the npz by dividing by 200, I got the same effect. I've attached an example NPZ here so you can take a look. 
[Eliot_Point17_row_0_col_0.npz.zip](https://github.com/vanvalenlab/caliban/files/4316487/Eliot_Point17_row_0_col_0.npz.zip)

**Comment by ngreenwald** [comment]
So it's not a dtype issue: the preivous IF data has the same dtype and doesn't have this problem. Perplexing. Here's the one I used before that doesn't have display issues: 
[cHL_Point8908e4f1e7974ba6b9ec6370a12b6678_row_0_col_0.npz.zip](https://github.com/vanvalenlab/caliban/files/4321030/cHL_Point8908e4f1e7974ba6b9ec6370a12b6678_row_0_col_0.npz.zip)

**Comment by MekWarrior** [comment]
I have seen this error before in other data. It can be an artifact of processing raw data. During one of the operations, the original data is saved with a lower dtype or processed outside of python and by the time it is saved at the end (with the correct dtype) the resolution has already been degraded. Is it possible to build a new npz using the original raw data?

**Comment by ngreenwald** [comment]
I tried that, didn't seem to make a difference. This is going through the same pipeline as everything else, including other int32 channels, so I'm not sure why this one in particular is different. 

If I load that NPZ, and imshow the channels, it looks fine. It's only in caliban that it looks like that

**Comment by ngreenwald** [comment]
You were right, it was the rescale_intensity function that was causing the problems. Specifically, this IF data has crazy high max values in a small subset of the pixels, and the max in the array is around 12k. However, the vast majority of the data is between 100 and 500 in counts. So when this gets rescaled by the max, and then converted to uint8, almost none of the range is getting used for the actual values we care about. 

The easiest way to fix this is to a percentile scaling instead of max scaling

**Comment by geneva-miller** [comment]
Between the 95 percentile scaling and the additional image display refactoring, I think this issue is resolved.
