### ISSUE TITLE
browser saves file locally as well as uploading to s3

### ISSUE THREAD

**Issue by geneva-miller** [vanvalenlab/caliban#106]
I think this is a bug. Submitting a file via browser Caliban should upload it to s3 and remove it from the database, but not write the saved file to disk. I think it comes from the lines of action_save_zstack:

```
        # save secure version of data before storing on regular file system
        file = secure_filename(save_file)

        np.savez(file, raw = self.raw, annotated = self.annotated)
        path = self.subfolders
        s3.upload_file(file, self.output_bucket, path)
```

Probably, "file" should be a file-like object that is not actually written to disk.

**Comment by willgraf** [comment]
Closed by #139
