### ISSUE TITLE
Add .DS_Store to .gitignore and remove them from the repo

### ISSUE THREAD

**Issue by willgraf** [vanvalenlab/caliban#107]
`caliban/desktop/.DS_Store` is tracked in git. This is an OSX file tracking metadata for folders and does not belong in git.

**Comment by willgraf** [comment]
Closing this as it seems to be resolved.

**Comment by geneva-miller** [comment]
I don't think this actually got resolved, `.DS_Store` is still in the `desktop` folder (this perhaps appeared resolved because `.DS_Store` isn't in any other folders).
