### ISSUE TITLE
Save user settings in MySQL to better profile successful jobs.

### ISSUE THREAD

**Issue by willgraf** [vanvalenlab/caliban#109]
It seems like our users are having a hard time with some of the jobs. While I think we have a decent guess of why these jobs are taking too long (based on our own user experience), it might be good to save any user settings for each job, along with the time it took to complete the job (#71).

I think this could be helpful in looking into any common issues users have while working on these jobs.

**Comment by geneva-miller** [comment]
Settings would need to be stored in a different table (?) since uploading a file also causes the corresponding object to be deleted from the database.

**Comment by geneva-miller** [comment]
Having just the time taken per file would be a helpful first step for accurately pricing jobs, but I am unfamiliar with SQL and unsure about how to implement this.

**Comment by willgraf** [comment]
We can create a couple of columns, `createdAt` and `updatedAt`, to track the timestamps. A nice thread about it [here](https://stackoverflow.com/questions/3488536/mysql-create-time-and-update-time-timestamp).

**Comment by geneva-miller** [comment]
To clarify, what I am uncertain about is how we should add another table to what we currently have (or whatever approach you think would work better). Is this something you could take a stab at, or could walk me through? Implementing the SQL code to do so is not intuitive to me.

**Comment by geneva-miller** [comment]
I've pushed a branch (browser/feature/timestamp_tracking) with a first pass attempt at implementing this. @willgraf I'd appreciate it if you could take a look at it before I try running it.

**Comment by geneva-miller** [comment]
A preliminary version of this is now deployed, which tracks timestamps for opening, updating, and submitting the file. @MekWarrior @willgraf  What other metrics do y'all think could be helpful here? Ones I am thinking of include:
-longest time between updates (someone steps away from file in the middle of it?)
-number of updates (increment each time the file is updated, as a proxy for how much "work" each file takes)
-don't update "updatedAt" timestamp when file is submitted (will show us time between last action and file submission)
-time between file creation and first update (proxy for time spent reading instructions)

**Comment by willgraf** [comment]
To implement some of the above will take a bit of extra effort, as the `updatedAt` field I created by default is automatically updated every time there is a change.  It will not be as simple to update it occasionally.

That said, we could add `firstUpdate` and `lastUpdate` timestamps that we update manually at the given times.

Otherwise, maybe consider:
- objects per image
- total updates
- count of mistakes? like undos or erases or something?
- average brush size
- ....?

**Comment by geneva-miller** [comment]
I think the metrics from #124 should be sufficient, but we can return to this later if needed.
