### ISSUE TITLE
label overlay makes it hard to see dim channels

### ISSUE THREAD

**Issue by ngreenwald** [vanvalenlab/caliban#114]
When the label overlay view is turned on, it makes it hard to see dim channels in RGB mode. I'm not sure if the scaling actually changes as a result of the white pixels being displayed (likely with a value of 255), or if it's just the contrast between them makes it harder to see by eye.

**Comment by geneva-miller** [comment]
RGB display is something that I'd like to revisit, but just taking a cursory look at it I'm pretty sure the underlying image is not changed by displaying overlaid label outlines. After whatever adjustments to the raw image are applied, any pixels corresponding to label boundaries are set to white (255, 255, 255) while all other pixels remain the same. So I think it's just a contrast issue.

**Comment by ngreenwald** [comment]
Yeah, you're definitely right, I was able to 90% solve this by ramping up the contrast adjustment.
