### ISSUE TITLE
specifying data format to caliban

### ISSUE THREAD

**Issue by ngreenwald** [vanvalenlab/caliban#118]
As the number of different data shapes expands, I'm wondering what the best way to record that metadata would be?

For example, for RGB data we have rows, cols, channels. 
For 3D stacks we have stacks, rows, cols, channels. 

Because the data is the array always has the same shape, we'll need to add in keywords specifying what the end format of the data should be. We'll likely want to pass this to caliban somehow as well?

**Comment by geneva-miller** [comment]
I'm not sure what you mean by this. Caliban should be saving data in the same shape it was in originally, even if the data needs to be squeezed/padded to open it. If you are referring to questions like "if I am working with 2D data, how do I tell the program not to display information about frames/slices?" I am kind of thinking we should add a config file where users can specify their defaults + the option of using command line flags like "-rgb". Don't have any concrete plans though. Not sure if this is something we can easily encode in the file itself.

**Comment by ngreenwald** [comment]
Exactly, not displaying frames/slices, displaying channels as RGB, etc.
Config file could work too!

**Comment by ngreenwald** [comment]
Okay, so circling back to this, the current setup of the toolbox saves npzs with the following dimensions: [slices, crops, rows, cols, channels]. So a typical 2D image would be [1, 1, 200, 200, 3] for example, and a stack might be [10, 1, 200, 200, 1]. 

Caliban doesn't currently accept 5D, so I've over-ridden this temporarily to just produce [1, 200, 200, 3] for 2D data. 

Do you think it makes more sense to have caliban take 5D input and squeeze to display properly, or change the output of the toolbox to be [slices, rows, cols, channels]?

For the toolbox itself we obviously need to store crops and slices on different axes, given that we may be slicing and cropping the same image and need to separately keep track of them. However, I don't think we'll ever have multiple crops in the same NPZ, so maybe this dimension isn't necessary for the NPZ? Either is equally easy for me, just let me know what you think makes more sense.

**Comment by ngreenwald** [comment]
Duplicate of #153
