### ISSUE TITLE
add pytest to repo

### ISSUE THREAD

**Issue by geneva-miller** [vanvalenlab/caliban#125]
We need to use either an older version of pytest, or change to a newer version of Flask to make this work: https://github.com/pytest-dev/pytest/issues/5532

**Comment by willgraf** [comment]
I would much prefer to upgrade flask than downgrade pytest. It seems that they did [release a version of flask that fixes the issue](https://github.com/pytest-dev/pytest/issues/5532#issuecomment-508882006).

**Comment by willgraf** [comment]
Closed by #144
