### ISSUE TITLE
Contour outlines don't update until brush action is finished

### ISSUE THREAD

**Issue by ngreenwald** [vanvalenlab/caliban#128]
I think this was done to reduce traffic between frontend and backend. If the shading that is currently used instead of the outline was more obvious this wouldn't be a big deal, but as it currently stands I think it's too subtle, so it's hard to see what's been drawn already

**Comment by geneva-miller** [comment]
Exactly. The outlines are calculated on the server and I don't foresee doing that in the frontend. I can definitely bump up the opacity of the brush shadow to address this. Slightly dimming the image (scroll wheel) may also help.

**Comment by geneva-miller** [comment]
Closing this issue due to #136 (brush drawing with a higher opacity)
