### ISSUE TITLE
Independent channel intensity scaling

### ISSUE THREAD

**Issue by ngreenwald** [vanvalenlab/caliban#145]
The current version of browser only allows for a uniform scaling adjustment across channels. There are frequently times when one channel is much brighter than another, and so dimming a single channel in isolation can be useful. I think it would be worth adding this from desktop at some point.

**Comment by geneva-miller** [comment]
See #127. Also, is this something that we want typical annotators to use? I'm a little wary about putting this in right away as I think it would not be user friendly.

**Comment by ngreenwald** [comment]
Ah woops, missed the duplicate.
What about the option to just completely turn off a given channel? It would
require a server call, but would potentially be easier to explain?
