### ISSUE TITLE
Standardizing raw/annotated vs X/y nomenclature across the pipeline

### ISSUE THREAD

**Issue by ngreenwald** [vanvalenlab/caliban#156]
We currently have certain places where we refer to images as X and labels as y, and other places where we refer to images as raw and labels as annotated. 

It looks like caliban is using raw/annotated, whereas the toolbox is using X/y. We should standardize them, I'm equally happy with either.

**Comment by willgraf** [comment]
I would prefer to standardize with `X` and `y`, since they are Keras standards already.

**Comment by geneva-miller** [comment]
Caliban uses `X` and `y` if provided but can also use `raw` and `annotated`--I think this was due to working with trk files which don't use `X` and `y`.

**Comment by ngreenwald** [comment]
Right, but it currently returns raw and annotated as NPZ labels no matter
what they were supplied as.

**Comment by geneva-miller** [comment]
Ah, my bad. That should be a pretty quick fix to save them as X and y instead.

**Comment by ngreenwald** [comment]
Sweet, thanks
