### ISSUE TITLE
return npz with 'X' and 'y' instead of 'raw' and 'annotated'

### ISSUE THREAD

**Issue by ngreenwald** [vanvalenlab/caliban#160]
Currently caliban has the old nomenclature for the created NPZs. To standardize the pipeline it would be nice to switch to X/y, or at least use whichever name the input npz has

**Comment by geneva-miller** [comment]
Browser caliban will now save all npzs with `X` and `y` whereas desktop caliban uses `raw` and `annotated` if those were the variable names, and `X` and `y` otherwise. There shouldn't be any situation where a file loaded from `X` and `y` gets saved with different variable names.
