### ISSUE TITLE
Flask request.args casts all boolean args to True.

### ISSUE THREAD

**Issue by willgraf** [vanvalenlab/caliban#161]
I learned a bit about how Flask casts the request args. `request.args` returns a `MultiDict` which has a [`.get` method](https://github.com/pallets/werkzeug/blob/6accf1f85f4dd5662e4c7f8ab6b115ed13037374/src/werkzeug/datastructures.py#L235).  This allows a `type` parameter, which we've set to boolean.

```python
# what we do in the route
label_only = request.args.get('label_only', type=bool)

# which is the same as
label_only = reqargs.get('label_only')  # string by default, as its from a URL
label_only = bool(label_only)
```

Which is a problem because:

```python
assert bool('True') is True and bool('False') is True
```

---

It looks like `flask_restful` uses `flask_restful.inputs.boolean` to [fix this problem](https://github.com/flask-restful/flask-restful/issues/397).

_Originally posted by @willgraf in https://github.com/vanvalenlab/caliban-toolbox/pull/79#issuecomment-619197035_

**Comment by willgraf** [comment]
Closed by #163

**Comment by ngreenwald** [comment]
Just tried a new job, this appears to still be an issue:
https://caliban.deepcell.org/caliban-input__caliban-output__multiplex__Human_Comparison__Eliot__Bri__first_pass__fov_Eliot_Point17_row_1_col_1_slice_0.npz?rgb=True&pixel_only=True&label_only=False

**Comment by ngreenwald** [comment]
Changes just hadn't been propagated yet, Geneva updated it, working as intended.
