### ISSUE TITLE
Add new mask to annotation

### ISSUE THREAD

**Issue by geneva-miller** [vanvalenlab/caliban#20]
Useful in cases where annotation is incorrect (missing pixels) or user has erroneously deleted a cell mask in a frame.

This option should:

- require user input to determine where annotation should be created
    - two clicks to determine corners of bounding box that contains cell to be annotated
    - third click to determine seed location for watershed transform
- create new mask in that frame using largest cell value in movie + 1 (new unique mask)
- create new lineage information corresponding to cell mask

**Comment by MekWarrior** [comment]
Solved by #31
