### ISSUE TITLE
Watershed clears nearby cell masks

### ISSUE THREAD

**Issue by geneva-miller** [vanvalenlab/Caliban#3]
When using watershed to separate one mask into two (eg cell 1 -> cell 1 and cell 2), nearby cells will have portions of their segmentation masks overwritten (ie, a chunk of cell 3 that is near cell 1 goes missing). These masks should be left unmodified by watershed.

**Comment by MekWarrior** [comment]
Bounding box where transform is calculated is directly inserted back into original image. This approach erroneously assumes that the bounding box only contains the label of interest. Issue resolved by using np.where to only copy pixels containing the label to be split.
