### ISSUE TITLE
cell_display info crashes when cell 1 not present

### ISSUE THREAD

**Issue by ngreenwald** [vanvalenlab/caliban#37]
https://github.com/vanvalenlab/caliban/blob/2a9af44325324ff678845e838b5cc9d3537b6f1d/desktop/caliban.py#L629

The line of code above looks in the dictionary associated with cell 1 to get the parameter names. If the mask is missing cell 1 the program crashes. Could change to either take the first cell id present, or a random cell id

**Comment by geneva-miller** [comment]
Fixed with #36
