### ISSUE TITLE
watershed only works when multiple cells selected

### ISSUE THREAD

**Issue by ngreenwald** [vanvalenlab/caliban#43]
https://github.com/vanvalenlab/caliban/blob/2a9af44325324ff678845e838b5cc9d3537b6f1d/desktop/caliban.py#L233

Is there a reason that watershed only works with multiple cells selected? This seems like it would be more likely to cause problems than requiring only one cell be selected

**Comment by geneva-miller** [comment]
You can select the same cell twice. When clicking on a label to select it, the x,y position of the click is stored. Watershed uses the two locations as seed values to separate a label, which is why it requires self.mode.kind == "MULTIPLE"

**Comment by ngreenwald** [comment]
Got it!
