### ISSUE TITLE
change watershed to work on currently selected channel

### ISSUE THREAD

**Issue by ngreenwald** [vanvalenlab/caliban#44]
https://github.com/vanvalenlab/caliban/blob/2a9af44325324ff678845e838b5cc9d3537b6f1d/desktop/caliban.py#L427

Currently watershed operates over a tensor of all features/channels combined. I think the behavior for multi-channel data would be more straightforward if instead it was changed to watershed over the currently selected channel. We could index into the img_array with the current feature; does this make sense?

**Comment by ngreenwald** [comment]
Okay so it turns out this actually already happening. I'm not sure why watershed is performing so poorly on MIBI data.

**Comment by geneva-miller** [comment]
Closing this issue because watershed does work on the current channel, and other updates (conversion brush, watershed failsafe) make this less of a problem.
