### ISSUE TITLE
Corrupted .npz file after sending to S3 bucket

### ISSUE THREAD

**Issue by jannieyu** [vanvalenlab/caliban#48]
.npz file isn't being properly fed to S3 bucket. Had same issue before when sending .trk file, but that has been fixed and resolved. Look into TrackReview class at load()/loadtrk() for solutions.

**Comment by geneva-miller** [comment]
Looks like the main difference in TrackReview when saving is file = secure_filename(self.filename). I don't see substantive differences in how the files are loaded. How did you discover that the .npzs were corrupted?

**Comment by jannieyu** [comment]
I took an .npz file from the output bucket and tried to see if I can view it again.

Latest push to caliban_browser branch fixed this bug. The key was to add the secure_filename(self.filename) line.

**Comment by geneva-miller** [comment]
Closed with #63
