### ISSUE TITLE
add keybind to cycle backwards through channels

### ISSUE THREAD

**Issue by geneva-miller** [vanvalenlab/caliban#49]
Currently, "c" advances the channel being viewed. It would be nice to add another keybind, perhaps shift+c, to cycle through channels in the other direction. That way, with npzs that contain >2 channels, contributors don't need to cycle through all of the channels to get back to a previous channel.

**Comment by jannieyu** [comment]
Keybind has been added to caliban_browser branch. 

For future reference, to add any keybind that is shift-[key], you only need to listen for the capital key letter.

**Comment by geneva-miller** [comment]
Added in #63. Only works in npz mode (trk files should never have more than one channel), use shift+c to go backwards through channels.
