### ISSUE TITLE
Browser Caliban should be able to load files from bucket even if they are not in a subfolder

### ISSUE THREAD

**Issue by geneva-miller** [vanvalenlab/caliban#50]
I'm having trouble loading the npz file we use for testing (caliban-input/test.npz, no subfolders). This may be because the landing page for Caliban has not been updated to reflect the new way of accessing files (where input_bucket, output_bucket, and folder structure are encoded in the url). The caliban website should be updated so that the dropdown list of files leads to working caliban sessions. This may not be the issue, but we should also check that caliban is able to access files even if they aren't in subfolders in the s3 bucket.

**Comment by jannieyu** [comment]
The dropdown list of files on the landing page are now all preloaded into a subfolder called 'test' in the input S3 bucket. To add more files to the landing page, developers only need to 

1. Update the dropdown menu in form.html to add the file option to the list
2. Upload the file to the 'test' subfolder in our S3 bucket.

**Comment by jannieyu** [comment]
Also, verified that Caliban is able to access files even if they are not in subfolders in S3 bucket. For example, calling something like http://0.0.0.0:5000/caliban-input__caliban-output__test.npz will work as long as test.npz is in the input S3 bucket and is not in a subfolder.

**Comment by geneva-miller** [comment]
Implemented in #63, note that uploading scripts such as in deepcell-toolbox will need to account for this when creating links to files. The format for the filenames that browser caliban can open is:
"{input bucket}__{output bucket}__{subfolders separated with __}__{filename.npz or .trk}". Each field is separated by two underscores, and the file can be in an arbitrary number of nested subfolders as long as each folder name is also separated with "__".
