### ISSUE TITLE
submit button should look more like a button

### ISSUE THREAD

**Issue by geneva-miller** [vanvalenlab/caliban#59]
The button to submit a file just looks like text. This should be visually updated to more obviously be the submit button.

Also, we should consider adding a confirmation dialog to the button in case of misclick.

**Comment by geneva-miller** [comment]
The text is bolded for both trk and npz mode as of #72, which helps, but I'd still like this to look like a button.

**Comment by geneva-miller** [comment]
Current submit button:
![image](https://user-images.githubusercontent.com/45578681/79153116-31073d80-7d82-11ea-95c9-04bcf98d161d.png)
After pressing:
![image](https://user-images.githubusercontent.com/45578681/79153161-43817700-7d82-11ea-88e3-e290ccccedd5.png)
Upon submission, the file is removed from the db so no more changes can be made. For this reason, I think a confirmation dialog would be a nice touch but I would consider that optional.

**Comment by willgraf** [comment]
This was closed by #154
