### ISSUE TITLE
add timestamps to db rows

### ISSUE THREAD

**Issue by geneva-miller** [vanvalenlab/caliban#71]
Would help to determine which rows in the database can be deleted without causing problems (eg, if a row hasn't been updated in a week). Not urgent but may be useful as browser caliban sees more traffic, as files won't necessarily be submitted each time they are opened (eg, demos, debugging, checking fig8 results), which will lead to rows that never get deleted from db.

**Comment by willgraf** [comment]
You might try to add a new field `updated_at` like so:

```
`updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
```

**Comment by geneva-miller** [comment]
For annotation metrics/monitoring, adding in a "first click" timestamp as well as a "file submitted" timestamp would be helpful. (Maybe also a "number of clicks" metric?) We probably still also want a "last accessed" timestamp to be able to easily clear stale rows from db.

Note: since the rows get deleted upon finishing the annotation, saving the file should also trigger the first click, file submitted, and number of clicks info to get saved or logged.... somewhere?
