### ISSUE TITLE
"c- relabel selected cell with an unused label" doesn't work in npz mode

### ISSUE THREAD

**Issue by ngreenwald** [vanvalenlab/caliban#76]
https://github.com/vanvalenlab/caliban/blob/23e8aa39cafa4fdb3909c5e7c2945882edb3c96d/desktop/caliban.py#L352

When relabeling a cell in npz mode, all cells that have that label get moved to a new label, rather than just one of those cells. 

Perhaps this isn't how we're supposed to be using c?
As it currently stands, if a single cell needs to be split into two cells, if we erase half of the cell, pick an arbitrary label for the new second half of the cell, and then select the new cell and use c to relabel it, both that cell and whatever other cell happens to also have that label will get moved to a new, unused channel. 

Let me know if there's a better way to be doing this!

**Comment by geneva-miller** [comment]
Most of the actions in not-edit mode affect all of the pixels in the frame with that label, even if they aren't contiguous. So I think in this case, C is performing as expected.

Fortunately, some actions that affect only contiguous labels have been added to desktop npz mode. Holding down the ctrl key while clicking on a label gives you the option of flooding the contiguous region of that label with an unused value. This will probably be the quickest way to fix duplicate labels if you have any remaining. To avoid this situation, you can now press "n" while in edit mode to set the brush to an unused label.

(The other action that affects contiguous labels is shift+click, which trims away unconnected pixels from the label you click on. Probably not useful for you in this case, but figured I'd mention it.)

Hope that helps!

**Comment by ngreenwald** [comment]
That's great! Both N and ctrl-clicking are super useful features. I'm
making a condensed version of the readme for our lab, i'll be sure to put
those in.

**Comment by ngreenwald** [comment]
I also remember seeing a pull request somewhere that added functionality for merging two cells together; is there a key binding for that?

**Comment by geneva-miller** [comment]
I'm not sure what you mean by that. Perhaps you're thinking of the replace function (select two different cells, prompt with r) which can be used in all frames or just a single frame for npzs?

**Comment by ngreenwald** [comment]
Yup, that's exactly it!
