### ISSUE TITLE
caliban crashes when no cells in image

### ISSUE THREAD

**Issue by ngreenwald** [vanvalenlab/caliban#85]
https://github.com/vanvalenlab/caliban/blob/39a1da01f23bb8fdc2be8f15b4a7c7edd8ddcfbd/desktop/caliban.py#L2325

When there aren't any cells in the FOV, this line causes caliban desktop to crash

**Comment by geneva-miller** [comment]
See also #57 . I'm currently working on refactoring/cleaning up desktop caliban so a version that addresses this should be available within a few days.

**Comment by ngreenwald** [comment]
Got it, thanks!

**Comment by geneva-miller** [comment]
The version of desktop caliban on the branch desktop/refactor should be able to open npzs that don't have any labels. Most of the functionality/behavior on that branch should remain the same but there are minor changes here and there. Let me know if you encounter any problems with that branch or have questions about it, as it's still under development

**Comment by geneva-miller** [comment]
Closed by #87
