### ISSUE TITLE
Browser actions sometimes don't get sent correctly

### ISSUE THREAD

**Issue by geneva-miller** [vanvalenlab/caliban#86]
Unclear why this happens. Most of the time this is an annoying but harmless failure, and the action just needs to be tried again. However, this can also happen to file submission, so that the modified file doesn't actually get uploaded to the output s3 bucket, but in the frontend it appears to be submitted. (Also, there isn't a way to submit the file twice anyway.) We should figure out this occasional bug so that work isn't wasted.

**Comment by geneva-miller** [comment]
Adding as priority task as browser caliban is going to see heavier use soon. I think one way to approach this is to revisit how we check for successful actions.

**Comment by geneva-miller** [comment]
![image](https://user-images.githubusercontent.com/45578681/78176758-e563a400-7411-11ea-867e-7a7d421b3533.png)
These errors started happening a few seconds after elastic beanstalk autoscaled to add another instance to the environment. After that, each request (changing frames and swapping labels) alternated between succeeding and failing (first one would fail, next would succeed) until 504 error. After that, all requests have been succeeding.

**Comment by willgraf** [comment]
Nice find! I would assume that the new instance is not yet ready so it is serving 404s?

**Comment by willgraf** [comment]
Maybe check out the [CloudWatch logs](https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/elb-cloudwatch-metrics.html#ViewingDataUsingCloudWatch) during the scale up to see if anything looks fishy?

**Comment by geneva-miller** [comment]
https://serverfault.com/questions/762425/504s-on-elastic-beanstalk-app-deploy-user-elb-elastic-beanstalk-mod-wsgi

Sounds like we may need to add a health check endpoint to the app?

**Comment by geneva-miller** [comment]
Okay, I've found where to configure the health check endpoint, but am pretty iffy on what to actually write for that route in flask. @willgraf do you have any examples or guidelines you could send me?

**Comment by willgraf** [comment]
I think you can just make an endpoint `/health-check` that returns a 200 status code with a body of "OK".

There's also [this package](https://pypi.org/project/py-healthcheck/) that looks like more than we need. I've never used it but seems cool.

**Comment by willgraf** [comment]
Closed by #139
