### ISSUE TITLE
watershed failsafe

### ISSUE THREAD

**Issue by ngreenwald** [vanvalenlab/caliban#94]
Watershed seems to be working great most of the time. However, the most common error mode seems to be that the two selected seed regions are not separated by a valley of lower intensity, and instead lie on a monotonically decreasing slope. Thus, when watershed is run, the point that is strictly higher ends up consuming the entire cell, leaving only a single point that is assigned to the second cell. 

This is not ideal, because it requires that the user then go in, and conversion brush that single pixel away, which must carefully be clicked on in order to be selected in the first place.

I have a couple potential solutions. The first would be to check whether or not the resulting watershed produces an object with fewer than 5 pixels, and if so to not update the labels, returning an error message instead. 

The other would be to check if that happens, and if so do a naive pixel expansion around the smaller object, so that it is at least big enough to interact with easily

**Comment by geneva-miller** [comment]
#129 adds a pixel dilation if either part of the split label (old or new value) is < 5 pixels large. Between that and the ability to zoom in on the (still pretty small) part of the label, I think bad watersheds are less painful to fix now.
