### ISSUE TITLE
more intuitive readout for color scaling

### ISSUE THREAD

**Issue by ngreenwald** [vanvalenlab/caliban#95]
Currently, when manual scaling is applied to a color overlay, the information on the left pane of caliban doesn't clearly communicate the scale level. For example, increasing the brightness of a channel results in increasingly negative numbers for that channel, and vice versa.

**Comment by geneva-miller** [comment]
I'm currently working on tidying up the image display code, and I think the direction I'm going to go with this is an actual multiplier, not additive adjustment. So after 95 percentile rescaling is applied to each channel, an adjustment of 1 = nothing changed, 0 = channel is totally dark, 2 = twice as bright. It seems to be working quite nicely. If you have any small suggestions/tweaks I can probably add those in.

**Comment by ngreenwald** [comment]
This is like driving a Cadillac. Scrolling adjustments are perfect
