### ISSUE TITLE
Border overlay is too thick

### ISSUE THREAD

**Issue by ngreenwald** [vanvalenlab/caliban#98]
The border overlay is currently multiple pixels thick. This obscures some of the underlying cell information. It would be great if the default was about half the current thickness, maybe even less. 

![image](https://user-images.githubusercontent.com/13770365/75518079-f81f2f00-59b4-11ea-8a75-bb636bf8f090.png)

**Comment by geneva-miller** [comment]
Yes, the default for skimage's find_boundaries function is 'thick' mode. I've pushed a commit to use the 'inner' mode which will reduce the boundary lines to one pixel in most places (boundaries between two labels will still be two pixels thick). Beyond that, I think toggling raw on/off with z is the best way to look at what the borders might be obscuring.
